# Generated by Django 3.1 on 2021-03-25 10:24


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36)),
                ('used', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('R', 'registration'), ('PR', 'password reset')], default='R', max_length=2)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='user_profile.userprofile')),
            ],
        ),
    ]
