# Generated by Django 3.1 on 2021-03-19 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='user_profile.UserProfile')),
                ('friends_with', models.ManyToManyField(blank=True, related_name='_userprofile_friends_with_+', to='user_profile.UserProfile')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
